#!/usr/bin/env bash
# Build execution images and pin their IDs in config/images.lock.yaml.
# Agent Manager launches only images listed there (ARCHITECTURE.md section 10).
# The lock is machine-specific (local image IDs), so it is not committed.
set -euo pipefail
cd "$(dirname "$0")/.."
VERSION="${HO_VERSION:-dev}"

build() {  # build <name> <dockerfile> <context>
  docker build -q -t "hermes-orchestrator/$1:$VERSION" -f "$2" "$3" >/dev/null
  docker image inspect --format '{{.Id}}' "hermes-orchestrator/$1:$VERSION"
}

AGENT_BASE=$(build agent-base workers/agent-base/Dockerfile workers/agent-base)
EGRESS_PROXY=$(build egress-proxy services/egress-proxy/Dockerfile .)

tmp="$(mktemp config/.images.lock.XXXXXX)"
cat > "$tmp" <<YAML
# Generated by scripts/build-images.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit.
# Pinned local image IDs that Agent Manager is allowed to launch.
images:
  agent-base: "$AGENT_BASE"
  egress-proxy: "$EGRESS_PROXY"
YAML
mv "$tmp" config/images.lock.yaml
cat config/images.lock.yaml
