#!/usr/bin/env bash
# Build execution images and pin their IDs in config/images.lock.yaml.
# Agent Manager launches only images listed there (ARCHITECTURE.md section 10).
# The lock is machine-specific (local image IDs), so it is not committed.
#
# Toolchain profiles compose (MASTER_SPEC section 18): each profile layer is
# built on top of the previous one, and each provider layer on top of that.
#   HO_TOOLCHAINS="generic node python node,python"   (default: "generic node python")
# builds, for every set S:  runner-S (tests), claude-S, and codex-S.
# Profiles: generic node python php java flutter. Versions: workers/versions.env.
set -euo pipefail
cd "$(dirname "$0")/.."
VERSION="${HO_VERSION:-dev}"
TOOLCHAINS="${HO_TOOLCHAINS:-generic node python}"
PROVIDERS="${HO_PROVIDERS:-claude codex}"
# shellcheck source=../workers/versions.env
source workers/versions.env
BUILD_ARGS=(--build-arg "NODE_IMAGE=$NODE_IMAGE" --build-arg "CLAUDE_CODE_VERSION=$CLAUDE_CODE_VERSION"
            --build-arg "CODEX_VERSION=$CODEX_VERSION" --build-arg "FLUTTER_VERSION=$FLUTTER_VERSION"
            --build-arg "FLUTTER_COMMIT=$FLUTTER_COMMIT")

declare -a LOCK=()
build() {  # build <name> <dockerfile> <context> [build args...]
  local name=$1 dockerfile=$2 context=$3
  shift 3
  echo "building $name" >&2
  docker build -q ${HO_PLATFORM:+--platform "$HO_PLATFORM"} -t "hermes-orchestrator/$name:$VERSION" -f "$dockerfile" \
    "${BUILD_ARGS[@]}" "$@" "$context" >/dev/null
  LOCK+=("  $name: \"$(docker image inspect --format '{{.Id}}' "hermes-orchestrator/$name:$VERSION")\"")
}
tag_of() { echo "hermes-orchestrator/$1:$VERSION"; }

build agent-base workers/agent-base/Dockerfile workers/agent-base
build egress-proxy services/egress-proxy/Dockerfile .
if [[ "${HO_BUILD_BROWSER:-1}" == "1" ]]; then
  # The verification scripts are shared with agent-base; the build context needs its own copies.
  cp workers/agent-base/ho-verify workers/agent-base/ho-wait-secrets workers/browser-runner/
  build browser-runner workers/browser-runner/Dockerfile workers/browser-runner
fi

DONE=" "  # toolchain chains already built (bash 3.2 compatible, no associative arrays)
for set in $TOOLCHAINS; do
  # Sorted, de-duplicated profile list; "generic" is the base itself.
  profiles=$(tr ',' '\n' <<<"$set" | { grep -v '^generic$' || true; } | sort -u | tr '\n' ' ')
  base=agent-base chain=""
  for profile in $profiles; do
    [[ -f workers/toolchains/$profile/Dockerfile ]] || { echo "unknown toolchain profile: $profile" >&2; exit 2; }
    chain="${chain:+$chain-}$profile"
    if [[ $DONE != *" $chain "* ]]; then
      build "toolchain-$chain" "workers/toolchains/$profile/Dockerfile" "workers/toolchains/$profile" \
        --build-arg "BASE=$(tag_of "$base")"
      DONE="$DONE$chain "
    fi
    base="toolchain-$chain"
  done
  suffix="${chain:-generic}"
  LOCK+=("  runner-$suffix: \"$(docker image inspect --format '{{.Id}}' "$(tag_of "$base")")\"")
  for provider in $PROVIDERS; do
    build "$provider-$suffix" "workers/providers/$provider/Dockerfile" "workers/providers/$provider" \
      --build-arg "BASE=$(tag_of "$base")" \
      --label "org.hermes-orchestrator.role=$provider-worker" --label "org.hermes-orchestrator.toolchains=$suffix"
  done
done

if [[ -n "${HO_PLATFORM:-}" ]]; then
  echo "built for $HO_PLATFORM with tag $VERSION (cross-platform build: config/images.lock.yaml left unchanged)" >&2
  exit 0
fi
tmp="$(mktemp config/.images.lock.XXXXXX)"
{
  echo "# Generated by scripts/build-images.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit."
  echo "# Pinned local image IDs that Agent Manager is allowed to launch."
  echo "versions:"
  echo "  claude-code: \"$CLAUDE_CODE_VERSION\""
  echo "  codex: \"$CODEX_VERSION\""
  echo "  toolchains: \"$TOOLCHAINS\""
  echo "images:"
  printf '%s\n' "${LOCK[@]}" | sort -u
} > "$tmp"
mv "$tmp" config/images.lock.yaml
cat config/images.lock.yaml
